# Defaults
backend = "glx"
inactive-opacity = 1;
active-opacity = 1;

# Custom opacity for terminal
opacity-rule = [
  "95:class_g = 'Alacritty' && focused",
  "75:class_g = 'Alacritty' && !focused"
];

corner-radius = 15

fading = true
fade-delta = 4
no-fading-openclose = false

blur-background = true
blur-method = "dual_kawase"
blur-strength = 6
