
# ZSH opts
unsetopt BEEP

# Add zsh config refs
source "$ZDOTDIR/zsh-functions"

zsh_add_file "zsh-exports"
zsh_add_file "zsh-prompt"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-history"

# Add zsh plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "agkozak/zsh-z"

# zstyle options

zstyle ':completion:*' menu select
zstyle ':completion:*' completer _extensions _complete _approximate

zmodload zsh/complist

eval "$(direnv hook zsh)"
