source "$ZDOTDIR/zsh-functions"

zsh_add_file "zsh-exports"
zsh_add_file "zsh-prompt"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-history"
zsh_add_file "zsh-options"
zsh_add_file "zsh-plugins"
zsh_add_file "zsh-task"
zsh_add_file "zsh-motd"

eval "$(direnv hook zsh)"
